// Generated by tiler-metal from verified structured kernel IR.
// Deterministic output: do not edit.
//
// Metal Shading Language: metal3.1
// Artifact family: macos (deployment minimum 14.0)
// Launch delivery realization: [[thread_position_in_grid]] declared as uint
// Structured index arithmetic: uint64_t, widened explicitly from uint delivery.
// Arithmetic subnormals, per floating-point type:
//   f32: flushes-to-zero-preserving-sign
//   f16: preserves-subnormals
//   bf16: flushes-to-zero-preserving-sign
//
// Carried by these operations under every math mode: every floating-point
// immediate is its exact bit pattern, every arithmetic operation is one
// statement, and every NaN test is an integer test over reinterpreted bits.
//
// Declared numerical obligations this profile cannot realize:
//   subnormal-flush-in-arithmetic
// Arithmetic types used with no stated subnormal fact: none.

#include <metal_stdlib>
using namespace metal;

// Replaces an arithmetic NaN with the canonical pattern 0x7fc00000.
//
// The predicate is an integer test over the reinterpreted bit pattern rather
// than a floating-point one, so no math-mode relaxation licence reaches it.
static inline float tiler_canonicalize_nan_f32_7fc00000(float value) {
    uint pattern = as_type<uint>(value);
    bool nan = (pattern & 0x7f800000u) == 0x7f800000u
        && (pattern & 0x007fffffu) != 0x00000000u;
    return nan ? as_type<float>(0x7fc00000u) : value;
}

// Entry point tiler_kernel_7df29a4b8093ae95
//   kernel identity digest: 7df29a4b8093ae95
//   scheduled region identity digest: 3167002b7b874c72
//   numerical profile: tiler.test.strict-f32
//   buffer(0): Input tensor, F32, Device space, Read access, 8 element(s)
//   buffer(1): Input tensor, F32, Device space, Read access, 12 element(s)
//   buffer(2): Output tensor, F32, Device space, Write access, 6 element(s)
kernel void tiler_kernel_7df29a4b8093ae95(
        device const float *b0 [[buffer(0)]],
        device const float *b1 [[buffer(1)]],
        device float *b2 [[buffer(2)]],
        uint tiler_global_invocation_index [[thread_position_in_grid]]) {
    uint64_t v0 = uint64_t(tiler_global_invocation_index);  // widened from uint
    uint64_t v1 = 6ul;
    bool v2 = v0 < v1;
    if (v2) {
        uint64_t v3 = 3ul;
        uint64_t v4 = v0 / v3;
        uint64_t v5 = 4ul;
        uint64_t v6 = v4 * v5;
        float v7 = b0[v6];  // bounds witness 0
        uint64_t v8 = 3ul;
        uint64_t v9 = v0 % v8;
        uint64_t v10 = 4ul;
        uint64_t v11 = v9 * v10;
        float v12 = b1[v11];  // bounds witness 1
        float v13 = v7 * v12;
        float v14 = tiler_canonicalize_nan_f32_7fc00000(v13);
        // serial loop over [1, 4)
        uint64_t v15 = 1ul;
        float v16 = v14;
        for (; v15 < 4ul; v15 = v15 + 1ul) {
            uint64_t v17 = 3ul;
            uint64_t v18 = v0 / v17;
            uint64_t v19 = 4ul;
            uint64_t v20 = v18 * v19;
            uint64_t v21 = v20 + v15;
            float v22 = b0[v21];  // bounds witness 0
            uint64_t v23 = 3ul;
            uint64_t v24 = v0 % v23;
            uint64_t v25 = 4ul;
            uint64_t v26 = v24 * v25;
            uint64_t v27 = v26 + v15;
            float v28 = b1[v27];  // bounds witness 1
            float v29 = v22 * v28;
            float v30 = tiler_canonicalize_nan_f32_7fc00000(v29);
            float v31 = v16 + v30;
            float v32 = tiler_canonicalize_nan_f32_7fc00000(v31);
            v16 = v32;
        }
        float v33 = v16;
        b2[v0] = v33;  // bounds witness 2, ownership witness 0
    }
}
