// Generated by tiler-metal from verified structured kernel IR.
// Deterministic output: do not edit.
//
// Metal Shading Language: metal3.1
// Artifact family: macos (deployment minimum 14.0)
// Launch delivery realization: [[thread_position_in_grid]] declared as uint
// Structured index arithmetic: uint64_t, widened explicitly from uint delivery.
// Arithmetic subnormals, per floating-point type:
//   f32: flushes-to-zero-preserving-sign
//   f16: preserves-subnormals
//   bf16: flushes-to-zero-preserving-sign
//
// Carried by these operations under every math mode: every floating-point
// immediate is its exact bit pattern, every arithmetic operation is one
// statement, and every NaN test is an integer test over reinterpreted bits.
//
// Declared numerical obligations this profile cannot realize:
//   subnormal-flush-in-arithmetic
// Arithmetic types used with no stated subnormal fact: none.

#include <metal_stdlib>
using namespace metal;

// Replaces an arithmetic NaN with the canonical pattern 0x7fc00000.
//
// The predicate is an integer test over the reinterpreted bit pattern rather
// than a floating-point one, so no math-mode relaxation licence reaches it.
static inline float tiler_canonicalize_nan_f32_7fc00000(float value) {
    uint pattern = as_type<uint>(value);
    bool nan = (pattern & 0x7f800000u) == 0x7f800000u
        && (pattern & 0x007fffffu) != 0x00000000u;
    return nan ? as_type<float>(0x7fc00000u) : value;
}

// Entry point tiler_kernel_7731e6147bc8e49b
//   kernel identity digest: 7731e6147bc8e49b
//   scheduled region identity digest: c8abcd6a458871a3
//   numerical profile: tiler.test.strict-f32
//   buffer(0): Input tensor, F32, Device space, Read access, 1280 element(s)
//   buffer(1): Input tensor, F32, Device space, Read access, 640 element(s)
//   buffer(2): Output tensor, F32, Device space, Write access, 1600 element(s)
//   tg0: F32, Workgroup space, 256 slot(s)
//   tg1: F32, Workgroup space, 256 slot(s)
kernel void tiler_kernel_7731e6147bc8e49b(
        device const float *b0 [[buffer(0)]],
        device const float *b1 [[buffer(1)]],
        device float *b2 [[buffer(2)]],
        uint tiler_global_invocation_index [[thread_position_in_grid]],
        uint tiler_local_invocation_index [[thread_index_in_threadgroup]]) {
    threadgroup float tg0[256];
    threadgroup float tg1[256];
    uint64_t v0 = uint64_t(tiler_global_invocation_index);  // widened from uint
    uint64_t v1 = uint64_t(tiler_local_invocation_index);  // widened from uint
    uint64_t v2 = 16ul;
    uint64_t v3 = 256ul;
    uint64_t v4 = 2ul;
    uint64_t v5 = 20ul;
    uint64_t v6 = 20ul;
    uint64_t v7 = 640ul;
    uint64_t v8 = 320ul;
    uint64_t v9 = 16ul;
    uint64_t v10 = v0 / v3;
    uint64_t v11 = v10 % v4;
    uint64_t v12 = v10 / v4;
    uint64_t v13 = 2ul;
    uint64_t v14 = v12 % v13;
    uint64_t v15 = v12 / v13;
    uint64_t v16 = 2ul;
    uint64_t v17 = v15 % v16;
    uint64_t v18 = v15 / v16;
    uint64_t v19 = v1 % v2;
    uint64_t v20 = v1 / v2;
    uint64_t v21 = v14 * v2;
    uint64_t v22 = v11 * v2;
    uint64_t v23 = v21 + v20;
    uint64_t v24 = v22 + v19;
    bool v25 = v23 < v5;
    bool v26 = v24 < v6;
    float v27 = as_type<float>(0x00000000u);
    uint64_t v28 = 0ul;
    uint64_t v29 = v28 + v19;
    uint64_t v30 = v28 + v20;
    uint64_t v31 = v18 * v7;
    uint64_t v32 = v17 * v8;
    uint64_t v33 = v23 * v9;
    uint64_t v34 = v18 * v8;
    uint64_t v35 = v24 * v9;
    uint64_t v36 = v31 + v32;
    uint64_t v37 = v36 + v33;
    uint64_t v38 = v37 + v29;
    uint64_t v39 = v34 + v35;
    uint64_t v40 = v39 + v30;
    float v41 = v25 ? b0[v38] : v27;  // bounds witness 0 on the guarded path
    float v42 = v26 ? b1[v40] : v27;  // bounds witness 1 on the guarded path
    uint64_t v43 = v20 * v2;
    uint64_t v44 = v43 + v19;
    uint64_t v45 = v19 * v2;
    uint64_t v46 = v45 + v20;
    tg0[v44] = v41;  // tile phase 0
    tg1[v46] = v42;  // tile phase 0
    threadgroup_barrier(mem_flags::mem_threadgroup);
    uint64_t v47 = v20 * v2;
    uint64_t v48 = v19 * v2;
    uint64_t v49 = 0ul;
    uint64_t v50 = v47 + v49;
    uint64_t v51 = v48 + v49;
    float v52 = tg0[v50];  // tile phase 1
    float v53 = tg1[v51];  // tile phase 1
    float v54 = v52 * v53;
    float v55 = tiler_canonicalize_nan_f32_7fc00000(v54);
    // serial loop over [1, 16)
    uint64_t v56 = 1ul;
    float v57 = v55;
    for (; v56 < 16ul; v56 = v56 + 1ul) {
        uint64_t v58 = v47 + v56;
        uint64_t v59 = v48 + v56;
        float v60 = tg0[v58];  // tile phase 1
        float v61 = tg1[v59];  // tile phase 1
        float v62 = v60 * v61;
        float v63 = tiler_canonicalize_nan_f32_7fc00000(v62);
        float v64 = v57 + v63;
        float v65 = tiler_canonicalize_nan_f32_7fc00000(v64);
        v57 = v65;
    }
    float v66 = v57;
    if (v25) {
        if (v26) {
            uint64_t v67 = v23 * v6;
            uint64_t v68 = v67 + v24;
            uint64_t v69 = 800ul;
            uint64_t v70 = v18 * v69;
            uint64_t v71 = v68 + v70;
            uint64_t v72 = 400ul;
            uint64_t v73 = v17 * v72;
            uint64_t v74 = v71 + v73;
            b2[v74] = v66;  // bounds witness 2, ownership witness 0
        }
    }
}
