// Generated by tiler-metal from verified structured kernel IR.
// Deterministic output: do not edit.
//
// Metal Shading Language: metal3.1
// Artifact family: macos (deployment minimum 14.0)
// Launch delivery realization: [[thread_position_in_grid]] declared as uint
// Structured index arithmetic: uint64_t, widened explicitly from uint delivery.
// Arithmetic subnormals, per floating-point type:
//   f32: flushes-to-zero-preserving-sign
//   f16: preserves-subnormals
//   bf16: flushes-to-zero-preserving-sign
//
// Carried by these operations under every math mode: every floating-point
// immediate is its exact bit pattern, every arithmetic operation is one
// statement, and every NaN test is an integer test over reinterpreted bits.
//
// Declared numerical obligations this profile cannot realize:
//   subnormal-flush-in-arithmetic
// Arithmetic types used with no stated subnormal fact: none.

#include <metal_stdlib>
using namespace metal;

// Replaces an arithmetic NaN with the canonical pattern 0x7fc00000.
//
// The predicate is an integer test over the reinterpreted bit pattern rather
// than a floating-point one, so no math-mode relaxation licence reaches it.
static inline float tiler_canonicalize_nan_f32_7fc00000(float value) {
    uint pattern = as_type<uint>(value);
    bool nan = (pattern & 0x7f800000u) == 0x7f800000u
        && (pattern & 0x007fffffu) != 0x00000000u;
    return nan ? as_type<float>(0x7fc00000u) : value;
}

// Entry point tiler_kernel_f4bec9ec1d6a846e
//   kernel identity digest: f4bec9ec1d6a846e
//   scheduled region identity digest: 2ecefc369c138064
//   numerical profile: tiler.test.strict-f32
//   buffer(0): Input tensor, F32, Device space, Read access, 320 element(s)
//   buffer(1): Input tensor, F32, Device space, Read access, 1024 element(s)
//   buffer(2): Output tensor, F32, Device space, Write access, 320 element(s)
//   tg0: F32, Workgroup space, 256 slot(s)
//   tg1: F32, Workgroup space, 256 slot(s)
kernel void tiler_kernel_f4bec9ec1d6a846e(
        device const float *b0 [[buffer(0)]],
        device const float *b1 [[buffer(1)]],
        device float *b2 [[buffer(2)]],
        uint tiler_global_invocation_index [[thread_position_in_grid]],
        uint tiler_local_invocation_index [[thread_index_in_threadgroup]]) {
    threadgroup float tg0[256];
    threadgroup float tg1[256];
    uint64_t v0 = uint64_t(tiler_global_invocation_index);  // widened from uint
    uint64_t v1 = uint64_t(tiler_local_invocation_index);  // widened from uint
    uint64_t v2 = 16ul;
    uint64_t v3 = 256ul;
    uint64_t v4 = 2ul;
    uint64_t v5 = 10ul;
    uint64_t v6 = 32ul;
    uint64_t v7 = 32ul;
    uint64_t v8 = v0 / v3;
    uint64_t v9 = v8 % v4;
    uint64_t v10 = v8 / v4;
    uint64_t v11 = v1 % v2;
    uint64_t v12 = v1 / v2;
    uint64_t v13 = v10 * v2;
    uint64_t v14 = v9 * v2;
    uint64_t v15 = v13 + v12;
    uint64_t v16 = v14 + v11;
    bool v17 = v15 < v5;
    bool v18 = v16 < v6;
    float v19 = as_type<float>(0x00000000u);
    uint64_t v20 = 0ul;
    uint64_t v21 = v20 + v11;
    uint64_t v22 = v20 + v12;
    uint64_t v23 = v15 * v7;
    uint64_t v24 = v16 * v7;
    uint64_t v25 = v23 + v21;
    uint64_t v26 = v24 + v22;
    float v27 = v17 ? b0[v25] : v19;  // bounds witness 0 on the guarded path
    float v28 = v18 ? b1[v26] : v19;  // bounds witness 1 on the guarded path
    uint64_t v29 = v12 * v2;
    uint64_t v30 = v29 + v11;
    uint64_t v31 = v11 * v2;
    uint64_t v32 = v31 + v12;
    tg0[v30] = v27;  // tile phase 0
    tg1[v32] = v28;  // tile phase 0
    threadgroup_barrier(mem_flags::mem_threadgroup);
    uint64_t v33 = v12 * v2;
    uint64_t v34 = v11 * v2;
    uint64_t v35 = 0ul;
    uint64_t v36 = v33 + v35;
    uint64_t v37 = v34 + v35;
    float v38 = tg0[v36];  // tile phase 1
    float v39 = tg1[v37];  // tile phase 1
    float v40 = v38 * v39;
    float v41 = tiler_canonicalize_nan_f32_7fc00000(v40);
    // serial loop over [1, 16)
    uint64_t v42 = 1ul;
    float v43 = v41;
    for (; v42 < 16ul; v42 = v42 + 1ul) {
        uint64_t v44 = v33 + v42;
        uint64_t v45 = v34 + v42;
        float v46 = tg0[v44];  // tile phase 1
        float v47 = tg1[v45];  // tile phase 1
        float v48 = v46 * v47;
        float v49 = tiler_canonicalize_nan_f32_7fc00000(v48);
        float v50 = v43 + v49;
        float v51 = tiler_canonicalize_nan_f32_7fc00000(v50);
        v43 = v51;
    }
    float v52 = v43;
    // serial loop over [1, 2)
    uint64_t v53 = 1ul;
    float v54 = v52;
    for (; v53 < 2ul; v53 = v53 + 1ul) {
        threadgroup_barrier(mem_flags::mem_threadgroup);
        uint64_t v55 = 16ul;
        uint64_t v56 = v53 * v55;
        uint64_t v57 = v56 + v11;
        uint64_t v58 = v56 + v12;
        uint64_t v59 = v15 * v7;
        uint64_t v60 = v16 * v7;
        uint64_t v61 = v59 + v57;
        uint64_t v62 = v60 + v58;
        float v63 = v17 ? b0[v61] : v19;  // bounds witness 0 on the guarded path
        float v64 = v18 ? b1[v62] : v19;  // bounds witness 1 on the guarded path
        uint64_t v65 = v12 * v2;
        uint64_t v66 = v65 + v11;
        uint64_t v67 = v11 * v2;
        uint64_t v68 = v67 + v12;
        tg0[v66] = v63;  // tile phase 0
        tg1[v68] = v64;  // tile phase 0
        threadgroup_barrier(mem_flags::mem_threadgroup);
        uint64_t v69 = v12 * v2;
        uint64_t v70 = v11 * v2;
        // serial loop over [0, 16)
        uint64_t v71 = 0ul;
        float v72 = v54;
        for (; v71 < 16ul; v71 = v71 + 1ul) {
            uint64_t v73 = v69 + v71;
            uint64_t v74 = v70 + v71;
            float v75 = tg0[v73];  // tile phase 1
            float v76 = tg1[v74];  // tile phase 1
            float v77 = v75 * v76;
            float v78 = tiler_canonicalize_nan_f32_7fc00000(v77);
            float v79 = v72 + v78;
            float v80 = tiler_canonicalize_nan_f32_7fc00000(v79);
            v72 = v80;
        }
        float v81 = v72;
        v54 = v81;
    }
    float v82 = v54;
    if (v17) {
        if (v18) {
            uint64_t v83 = v15 * v6;
            uint64_t v84 = v83 + v16;
            b2[v84] = v82;  // bounds witness 2, ownership witness 0
        }
    }
}
