// Generated by tiler-metal from verified structured kernel IR.
// Deterministic output: do not edit.
//
// Metal Shading Language: metal3.1
// Artifact family: macos (deployment minimum 14.0)
// Launch delivery realization: [[thread_position_in_grid]] declared as uint
// Structured index arithmetic: uint64_t, widened explicitly from uint delivery.
// Arithmetic subnormals, per floating-point type:
//   f32: flushes-to-zero-preserving-sign
//   f16: preserves-subnormals
//   bf16: flushes-to-zero-preserving-sign
//
// Carried by these operations under every math mode: every floating-point
// immediate is its exact bit pattern, every arithmetic operation is one
// statement, and every NaN test is an integer test over reinterpreted bits.
//
// Declared numerical obligations this profile cannot realize:
//   subnormal-flush-in-arithmetic
// Arithmetic types used with no stated subnormal fact: none.

#include <metal_stdlib>
using namespace metal;

// Replaces an arithmetic NaN with the canonical pattern 0x7fc00000.
//
// The predicate is an integer test over the reinterpreted bit pattern rather
// than a floating-point one, so no math-mode relaxation licence reaches it.
static inline float tiler_canonicalize_nan_f32_7fc00000(float value) {
    uint pattern = as_type<uint>(value);
    bool nan = (pattern & 0x7f800000u) == 0x7f800000u
        && (pattern & 0x007fffffu) != 0x00000000u;
    return nan ? as_type<float>(0x7fc00000u) : value;
}

// Entry point tiler_kernel_65f604a4e68d6f54
//   kernel identity digest: 65f604a4e68d6f54
//   scheduled region identity digest: 10414f99f46dd778
//   numerical profile: tiler.test.strict-f32
//   buffer(0): Input tensor, F32, Device space, Read access, 60 element(s)
//   buffer(1): Input tensor, F32, Device space, Read access, 40 element(s)
//   buffer(2): Output tensor, F32, Device space, Write access, 48 element(s)
kernel void tiler_kernel_65f604a4e68d6f54(
        device const float *b0 [[buffer(0)]],
        device const float *b1 [[buffer(1)]],
        device float *b2 [[buffer(2)]],
        uint tiler_global_invocation_index [[thread_position_in_grid]]) {
    uint64_t v0 = uint64_t(tiler_global_invocation_index);  // widened from uint
    uint64_t v1 = 48ul;
    bool v2 = v0 < v1;
    if (v2) {
        uint64_t v3 = 24ul;
        uint64_t v4 = v0 / v3;
        uint64_t v5 = 30ul;
        uint64_t v6 = v4 * v5;
        uint64_t v7 = 12ul;
        uint64_t v8 = v0 / v7;
        uint64_t v9 = 2ul;
        uint64_t v10 = v8 % v9;
        uint64_t v11 = 15ul;
        uint64_t v12 = v10 * v11;
        uint64_t v13 = v6 + v12;
        uint64_t v14 = 4ul;
        uint64_t v15 = v0 / v14;
        uint64_t v16 = 3ul;
        uint64_t v17 = v15 % v16;
        uint64_t v18 = 5ul;
        uint64_t v19 = v17 * v18;
        uint64_t v20 = v13 + v19;
        float v21 = b0[v20];  // bounds witness 0
        uint64_t v22 = 24ul;
        uint64_t v23 = v0 / v22;
        uint64_t v24 = 20ul;
        uint64_t v25 = v23 * v24;
        uint64_t v26 = 4ul;
        uint64_t v27 = v0 % v26;
        uint64_t v28 = v25 + v27;
        float v29 = b1[v28];  // bounds witness 1
        float v30 = v21 * v29;
        float v31 = tiler_canonicalize_nan_f32_7fc00000(v30);
        // serial loop over [1, 5)
        uint64_t v32 = 1ul;
        float v33 = v31;
        for (; v32 < 5ul; v32 = v32 + 1ul) {
            uint64_t v34 = 24ul;
            uint64_t v35 = v0 / v34;
            uint64_t v36 = 30ul;
            uint64_t v37 = v35 * v36;
            uint64_t v38 = 12ul;
            uint64_t v39 = v0 / v38;
            uint64_t v40 = 2ul;
            uint64_t v41 = v39 % v40;
            uint64_t v42 = 15ul;
            uint64_t v43 = v41 * v42;
            uint64_t v44 = v37 + v43;
            uint64_t v45 = 4ul;
            uint64_t v46 = v0 / v45;
            uint64_t v47 = 3ul;
            uint64_t v48 = v46 % v47;
            uint64_t v49 = 5ul;
            uint64_t v50 = v48 * v49;
            uint64_t v51 = v44 + v50;
            uint64_t v52 = v51 + v32;
            float v53 = b0[v52];  // bounds witness 0
            uint64_t v54 = 24ul;
            uint64_t v55 = v0 / v54;
            uint64_t v56 = 20ul;
            uint64_t v57 = v55 * v56;
            uint64_t v58 = 4ul;
            uint64_t v59 = v32 * v58;
            uint64_t v60 = v57 + v59;
            uint64_t v61 = 4ul;
            uint64_t v62 = v0 % v61;
            uint64_t v63 = v60 + v62;
            float v64 = b1[v63];  // bounds witness 1
            float v65 = v53 * v64;
            float v66 = tiler_canonicalize_nan_f32_7fc00000(v65);
            float v67 = v33 + v66;
            float v68 = tiler_canonicalize_nan_f32_7fc00000(v67);
            v33 = v68;
        }
        float v69 = v33;
        b2[v0] = v69;  // bounds witness 2, ownership witness 0
    }
}
