// Generated by tiler-metal from verified structured kernel IR.
// Deterministic output: do not edit.
//
// Metal Shading Language: metal3.1
// Artifact family: macos (deployment minimum 14.0)
// Launch delivery realization: [[thread_position_in_grid]] declared as uint
// Structured index arithmetic: uint64_t, widened explicitly from uint delivery.
// Arithmetic subnormals, per floating-point type:
//   f32: flushes-to-zero-preserving-sign
//   f16: preserves-subnormals
//   bf16: flushes-to-zero-preserving-sign
//
// Carried by these operations under every math mode: every floating-point
// immediate is its exact bit pattern, every arithmetic operation is one
// statement, and every NaN test is an integer test over reinterpreted bits.
//
// Declared numerical obligations this profile cannot realize:
//   subnormal-flush-in-arithmetic
// Arithmetic types used with no stated subnormal fact: none.

#include <metal_stdlib>
using namespace metal;

// Replaces an arithmetic NaN with the canonical pattern 0x7fc00000.
//
// The predicate is an integer test over the reinterpreted bit pattern rather
// than a floating-point one, so no math-mode relaxation licence reaches it.
static inline float tiler_canonicalize_nan_f32_7fc00000(float value) {
    uint pattern = as_type<uint>(value);
    bool nan = (pattern & 0x7f800000u) == 0x7f800000u
        && (pattern & 0x007fffffu) != 0x00000000u;
    return nan ? as_type<float>(0x7fc00000u) : value;
}

// Entry point tiler_kernel_3b7562146203d704
//   kernel identity digest: 3b7562146203d704
//   scheduled region identity digest: 541aa6337afc74f2
//   numerical profile: tiler.test.strict-f32
//   buffer(0): Input tensor, F32, Device space, Read access, 48 element(s)
//   buffer(1): Input tensor, F32, Device space, Read access, 40 element(s)
//   buffer(2): Output tensor, F32, Device space, Write access, 60 element(s)
kernel void tiler_kernel_3b7562146203d704(
        device const float *b0 [[buffer(0)]],
        device const float *b1 [[buffer(1)]],
        device float *b2 [[buffer(2)]],
        uint tiler_global_invocation_index [[thread_position_in_grid]]) {
    uint64_t v0 = uint64_t(tiler_global_invocation_index);  // widened from uint
    uint64_t v1 = 60ul;
    bool v2 = v0 < v1;
    if (v2) {
        uint64_t v3 = 30ul;
        uint64_t v4 = v0 / v3;
        uint64_t v5 = 24ul;
        uint64_t v6 = v4 * v5;
        uint64_t v7 = 15ul;
        uint64_t v8 = v0 / v7;
        uint64_t v9 = 2ul;
        uint64_t v10 = v8 % v9;
        uint64_t v11 = 12ul;
        uint64_t v12 = v10 * v11;
        uint64_t v13 = v6 + v12;
        uint64_t v14 = 5ul;
        uint64_t v15 = v0 / v14;
        uint64_t v16 = 3ul;
        uint64_t v17 = v15 % v16;
        uint64_t v18 = 4ul;
        uint64_t v19 = v17 * v18;
        uint64_t v20 = v13 + v19;
        float v21 = b0[v20];  // bounds witness 0
        uint64_t v22 = 30ul;
        uint64_t v23 = v0 / v22;
        uint64_t v24 = 20ul;
        uint64_t v25 = v23 * v24;
        uint64_t v26 = 5ul;
        uint64_t v27 = v0 % v26;
        uint64_t v28 = 4ul;
        uint64_t v29 = v27 * v28;
        uint64_t v30 = v25 + v29;
        float v31 = b1[v30];  // bounds witness 1
        float v32 = v21 * v31;
        float v33 = tiler_canonicalize_nan_f32_7fc00000(v32);
        // serial loop over [1, 4)
        uint64_t v34 = 1ul;
        float v35 = v33;
        for (; v34 < 4ul; v34 = v34 + 1ul) {
            uint64_t v36 = 30ul;
            uint64_t v37 = v0 / v36;
            uint64_t v38 = 24ul;
            uint64_t v39 = v37 * v38;
            uint64_t v40 = 15ul;
            uint64_t v41 = v0 / v40;
            uint64_t v42 = 2ul;
            uint64_t v43 = v41 % v42;
            uint64_t v44 = 12ul;
            uint64_t v45 = v43 * v44;
            uint64_t v46 = v39 + v45;
            uint64_t v47 = 5ul;
            uint64_t v48 = v0 / v47;
            uint64_t v49 = 3ul;
            uint64_t v50 = v48 % v49;
            uint64_t v51 = 4ul;
            uint64_t v52 = v50 * v51;
            uint64_t v53 = v46 + v52;
            uint64_t v54 = v53 + v34;
            float v55 = b0[v54];  // bounds witness 0
            uint64_t v56 = 30ul;
            uint64_t v57 = v0 / v56;
            uint64_t v58 = 20ul;
            uint64_t v59 = v57 * v58;
            uint64_t v60 = 5ul;
            uint64_t v61 = v0 % v60;
            uint64_t v62 = 4ul;
            uint64_t v63 = v61 * v62;
            uint64_t v64 = v59 + v63;
            uint64_t v65 = v64 + v34;
            float v66 = b1[v65];  // bounds witness 1
            float v67 = v55 * v66;
            float v68 = tiler_canonicalize_nan_f32_7fc00000(v67);
            float v69 = v35 + v68;
            float v70 = tiler_canonicalize_nan_f32_7fc00000(v69);
            v35 = v70;
        }
        float v71 = v35;
        b2[v0] = v71;  // bounds witness 2, ownership witness 0
    }
}
