// Generated by tiler-metal from verified structured kernel IR.
// Deterministic output: do not edit.
//
// Metal Shading Language: metal3.1
// Artifact family: macos (deployment minimum 14.0)
// Launch delivery realization: [[thread_position_in_grid]] declared as uint
// Structured index arithmetic: uint64_t, widened explicitly from uint delivery.
// Arithmetic subnormals, per floating-point type:
//   f32: flushes-to-zero-preserving-sign
//   f16: preserves-subnormals
//   bf16: flushes-to-zero-preserving-sign
//
// Carried by these operations under every math mode: every f32 immediate
// is its exact bit pattern, every arithmetic operation is one statement,
// and every NaN test is an integer test over reinterpreted bits.
//
// Declared numerical obligations this profile cannot realize:
//   subnormal-flush-in-arithmetic
// Arithmetic types used with no stated subnormal fact: none.

#include <metal_stdlib>
using namespace metal;

// Replaces an arithmetic NaN with the canonical pattern 0x7fc00000.
//
// The predicate is an integer test over the reinterpreted bit pattern rather
// than a floating-point one, so no math-mode relaxation licence reaches it.
static inline float tiler_canonicalize_nan_f32_7fc00000(float value) {
    uint pattern = as_type<uint>(value);
    bool nan = (pattern & 0x7f800000u) == 0x7f800000u
        && (pattern & 0x007fffffu) != 0x00000000u;
    return nan ? as_type<float>(0x7fc00000u) : value;
}

// Entry point tiler_kernel_1e4d242be12ef506
//   kernel identity digest: 1e4d242be12ef506
//   scheduled region identity digest: 246c37186376dc46
//   numerical profile: tiler.test.strict-f32
//   buffer(0): Intermediate tensor, F32, Device space, Read access, 12 element(s)
//   buffer(1): Output tensor, F32, Device space, Write access, 2 element(s)
//   tg0: F32, Workgroup space, 3 slot(s)
kernel void tiler_kernel_1e4d242be12ef506(
        device const float *b0 [[buffer(0)]],
        device float *b1 [[buffer(1)]],
        uint tiler_global_invocation_index [[thread_position_in_grid]],
        uint tiler_local_invocation_index [[thread_index_in_threadgroup]]) {
    threadgroup float tg0[3];
    uint64_t v0 = uint64_t(tiler_global_invocation_index);  // widened from uint
    uint64_t v1 = uint64_t(tiler_local_invocation_index);  // widened from uint
    uint64_t v2 = 3ul;
    uint64_t v3 = v0 / v2;
    uint64_t v4 = v0 % v2;
    uint64_t v5 = 6ul;
    bool v6 = v0 < v5;
    if (v6) {
        uint64_t v7 = 2ul;
        uint64_t v8 = v4 * v7;
        uint64_t v9 = 6ul;
        uint64_t v10 = v3 * v9;
        uint64_t v11 = v10 + v8;
        float v12 = b0[v11];  // bounds witness 0
        // serial loop over [1, 2)
        uint64_t v13 = 1ul;
        float v14 = v12;
        for (; v13 < 2ul; v13 = v13 + 1ul) {
            uint64_t v15 = 2ul;
            uint64_t v16 = v4 * v15;
            uint64_t v17 = v16 + v13;
            uint64_t v18 = 6ul;
            uint64_t v19 = v3 * v18;
            uint64_t v20 = v19 + v17;
            float v21 = b0[v20];  // bounds witness 0
            float v22 = v14 + v21;
            float v23 = tiler_canonicalize_nan_f32_7fc00000(v22);
            v14 = v23;
        }
        float v24 = v14;
        tg0[v1] = v24;  // tile phase 0
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (v6) {
        uint64_t v25 = 1ul;
        bool v26 = v1 < v25;
        if (v26) {
            uint64_t v27 = 0ul;
            float v28 = tg0[v27];  // tile phase 1
            // serial loop over [1, 3)
            uint64_t v29 = 1ul;
            float v30 = v28;
            for (; v29 < 3ul; v29 = v29 + 1ul) {
                float v31 = tg0[v29];  // tile phase 1
                float v32 = v30 + v31;
                float v33 = tiler_canonicalize_nan_f32_7fc00000(v32);
                v30 = v33;
            }
            float v34 = v30;
            b1[v3] = v34;  // bounds witness 1, ownership witness 0
        }
    }
}
