// Generated by tiler-metal from verified structured kernel IR.
// Deterministic output: do not edit.
//
// Metal Shading Language: metal3.1
// Artifact family: macos (deployment minimum 14.0)
// Launch index: [[thread_position_in_grid]] declared as uint
// Launch precondition: no invocation index may exceed 4294967295.
// Arithmetic subnormals, per floating-point type:
//   f32: flushes-to-zero-preserving-sign
//   f16: preserves-subnormals
//   bf16: flushes-to-zero-preserving-sign
//
// Carried by these operations under every math mode: every f32 immediate
// is its exact bit pattern, every arithmetic operation is one statement,
// and every NaN test is an integer test over reinterpreted bits.
//
// Declared numerical obligations this profile cannot realize:
//   subnormal-flush-in-arithmetic
// Arithmetic types used with no stated subnormal fact: none.

#include <metal_stdlib>
using namespace metal;

// Replaces an arithmetic NaN with the canonical pattern 0x7fc00000.
//
// The predicate is an integer test over the reinterpreted bit pattern rather
// than a floating-point one, so no math-mode relaxation licence reaches it.
static inline float tiler_canonicalize_nan_f32_7fc00000(float value) {
    uint pattern = as_type<uint>(value);
    bool nan = (pattern & 0x7f800000u) == 0x7f800000u
        && (pattern & 0x007fffffu) != 0x00000000u;
    return nan ? as_type<float>(0x7fc00000u) : value;
}

// Entry point tiler_kernel_230592073cdda0ac
//   kernel identity digest: 230592073cdda0ac
//   scheduled region identity digest: d08e6956eb53e496
//   numerical profile: tiler.test.strict-f32
//   buffer(0): Input tensor, F32, Device space, Read access, 4 element(s)
//   buffer(1): Intermediate tensor, F32, Device space, Write access, 4 element(s)
kernel void tiler_kernel_230592073cdda0ac(
        device const float *b0 [[buffer(0)]],
        device float *b1 [[buffer(1)]],
        uint tiler_global_invocation_index [[thread_position_in_grid]]) {
    ulong v0 = ulong(tiler_global_invocation_index);  // widened from uint
    ulong v1 = 4ul;
    bool v2 = v0 < v1;
    if (v2) {
        float v3 = b0[v0];  // bounds witness 0
        float v4 = as_type<float>(0x40000000u);
        float v5 = v3 * v4;
        float v6 = tiler_canonicalize_nan_f32_7fc00000(v5);
        float v7 = as_type<float>(0x3f800000u);
        float v8 = v6 + v7;
        float v9 = tiler_canonicalize_nan_f32_7fc00000(v8);
        b1[v0] = v9;  // bounds witness 1, ownership witness 0
    }
}
