// Generated by tiler-metal from verified structured kernel IR.
// Deterministic output: do not edit.
//
// Metal Shading Language: metal3.1
// Artifact family: macos (deployment minimum 14.0)
// Launch delivery realization: [[thread_position_in_grid]] declared as uint
// Structured index arithmetic: uint64_t, widened explicitly from uint delivery.
// Arithmetic subnormals, per floating-point type:
//   f32: flushes-to-zero-preserving-sign
//   f16: preserves-subnormals
//   bf16: flushes-to-zero-preserving-sign
//
// Carried by these operations under every math mode: every floating-point
// immediate is its exact bit pattern, every arithmetic operation is one
// statement, and every NaN test is an integer test over reinterpreted bits.
//
// Declared numerical obligations this profile cannot realize:
//   subnormal-flush-in-arithmetic
// Arithmetic types used with no stated subnormal fact: none.

#include <metal_stdlib>
using namespace metal;

// Replaces an arithmetic NaN with the canonical pattern 0x7fc0.
//
// The predicate is an integer test over the reinterpreted bit pattern rather
// than a floating-point one, so no math-mode relaxation licence reaches it.
static inline bfloat tiler_canonicalize_nan_bf16_7fc0(bfloat value) {
    ushort pattern = as_type<ushort>(value);
    bool nan = (pattern & 0x7f80u) == 0x7f80u
        && (pattern & 0x007fu) != 0x0000u;
    return nan ? as_type<bfloat>(ushort(0x7fc0u)) : value;
}

// Entry point tiler_kernel_a2df42e83503af57
//   kernel identity digest: a2df42e83503af57
//   scheduled region identity digest: cb12962007e495b7
//   numerical profile: tiler.test.strict-bf16
//   buffer(0): Input tensor, Bf16, Device space, Read access, 4 element(s)
//   buffer(1): Intermediate tensor, Bf16, Device space, Write access, 4 element(s)
kernel void tiler_kernel_a2df42e83503af57(
        device const bfloat *b0 [[buffer(0)]],
        device bfloat *b1 [[buffer(1)]],
        uint tiler_global_invocation_index [[thread_position_in_grid]]) {
    uint64_t v0 = uint64_t(tiler_global_invocation_index);  // widened from uint
    uint64_t v1 = 4ul;
    bool v2 = v0 < v1;
    if (v2) {
        bfloat v3 = b0[v0];  // bounds witness 0
        bfloat v4 = as_type<bfloat>(ushort(0x4000u));
        bfloat v5 = v3 * v4;
        bfloat v6 = tiler_canonicalize_nan_bf16_7fc0(v5);
        bfloat v7 = as_type<bfloat>(ushort(0x3f80u));
        bfloat v8 = v6 + v7;
        bfloat v9 = tiler_canonicalize_nan_bf16_7fc0(v8);
        b1[v0] = v9;  // bounds witness 1, ownership witness 0
    }
}
