// Generated by tiler-metal from verified structured kernel IR.
// Deterministic output: do not edit.
//
// Metal Shading Language: metal3.1
// Artifact family: macos (deployment minimum 13.0)
// Launch index: [[thread_position_in_grid]] declared as uint
// Launch precondition: no invocation index may exceed 4294967295.
//
// Every f32 immediate is emitted as its exact bit pattern, and every
// arithmetic operation is emitted as one statement, so neither literal
// parsing nor contraction across operations can change a result.

#include <metal_stdlib>
using namespace metal;

// Replaces an arithmetic NaN with the canonical pattern 0x7fc00000.
static inline float tiler_canonicalize_nan_f32_7fc00000(float value) {
    return isnan(value) ? as_type<float>(0x7fc00000u) : value;
}

// Entry point tiler_kernel_4e75d6dcce52e254
//   kernel identity digest: 4e75d6dcce52e254
//   scheduled region identity digest: ea4d348d458bfdf1
//   numerical profile: tiler.test.strict-f32
//   buffer(0): Input tensor, F32, Device space, Read access, 6 element(s)
//   buffer(1): Output tensor, F32, Device space, Write access, 2 element(s)
kernel void tiler_kernel_4e75d6dcce52e254(
        device const float *b0 [[buffer(0)]],
        device float *b1 [[buffer(1)]],
        uint tiler_global_invocation_index [[thread_position_in_grid]]) {
    ulong v0 = ulong(tiler_global_invocation_index);  // widened from uint
    ulong v1 = 2ul;
    bool v2 = v0 < v1;
    if (v2) {
        ulong v3 = 3ul;
        ulong v4 = v0 * v3;
        float v5 = b0[v4];  // bounds witness 0
        float v6 = as_type<float>(0x40000000u);
        float v7 = v5 * v6;
        float v8 = tiler_canonicalize_nan_f32_7fc00000(v7);
        float v9 = as_type<float>(0x3f800000u);
        float v10 = v8 + v9;
        float v11 = tiler_canonicalize_nan_f32_7fc00000(v10);
        // serial loop over [1, 3)
        ulong v12 = 1ul;
        float v13 = v11;
        for (; v12 < 3ul; v12 = v12 + 1ul) {
            ulong v14 = 3ul;
            ulong v15 = v0 * v14;
            ulong v16 = v15 + v12;
            float v17 = b0[v16];  // bounds witness 0
            float v18 = as_type<float>(0x40000000u);
            float v19 = v17 * v18;
            float v20 = tiler_canonicalize_nan_f32_7fc00000(v19);
            float v21 = as_type<float>(0x3f800000u);
            float v22 = v20 + v21;
            float v23 = tiler_canonicalize_nan_f32_7fc00000(v22);
            float v24 = v13 + v23;
            float v25 = tiler_canonicalize_nan_f32_7fc00000(v24);
            v13 = v25;
        }
        float v26 = v13;
        b1[v0] = v26;  // bounds witness 1, ownership witness 0
    }
}
