// Generated by tiler-metal from verified structured kernel IR.
// Deterministic output: do not edit.
//
// Metal Shading Language: metal3.1
// Artifact family: macos (deployment minimum 13.0)
// Launch index: [[thread_position_in_grid]] declared as uint
// Launch precondition: no invocation index may exceed 4294967295.
// f32 arithmetic subnormals: flushes-to-zero
//
// Carried by these operations under every math mode: every f32 immediate
// is its exact bit pattern, every arithmetic operation is one statement,
// and every NaN test is an integer test over reinterpreted bits.
//
// Declared numerical obligations this profile cannot realize:
//   subnormal-flush-in-arithmetic

#include <metal_stdlib>
using namespace metal;

// Replaces an arithmetic NaN with the canonical pattern 0x7fc00000.
//
// The predicate is an integer test over the reinterpreted bit pattern rather
// than a floating-point one, so no math-mode relaxation licence reaches it.
static inline float tiler_canonicalize_nan_f32_7fc00000(float value) {
    uint pattern = as_type<uint>(value);
    bool nan = (pattern & 0x7f800000u) == 0x7f800000u
        && (pattern & 0x007fffffu) != 0x00000000u;
    return nan ? as_type<float>(0x7fc00000u) : value;
}

// Entry point tiler_kernel_7cc43171ae13bcce
//   kernel identity digest: 7cc43171ae13bcce
//   scheduled region identity digest: c48427542a02afb5
//   numerical profile: tiler.test.strict-f32
//   buffer(0): Intermediate tensor, F32, Device space, Read access, 6 element(s)
//   buffer(1): Output tensor, F32, Device space, Write access, 2 element(s)
kernel void tiler_kernel_7cc43171ae13bcce(
        device const float *b0 [[buffer(0)]],
        device float *b1 [[buffer(1)]],
        uint tiler_global_invocation_index [[thread_position_in_grid]]) {
    ulong v0 = ulong(tiler_global_invocation_index);  // widened from uint
    ulong v1 = 2ul;
    bool v2 = v0 < v1;
    if (v2) {
        ulong v3 = 3ul;
        ulong v4 = v0 * v3;
        float v5 = b0[v4];  // bounds witness 0
        // serial loop over [1, 3)
        ulong v6 = 1ul;
        float v7 = v5;
        for (; v6 < 3ul; v6 = v6 + 1ul) {
            ulong v8 = 3ul;
            ulong v9 = v0 * v8;
            ulong v10 = v9 + v6;
            float v11 = b0[v10];  // bounds witness 0
            float v12 = v7 + v11;
            float v13 = tiler_canonicalize_nan_f32_7fc00000(v12);
            v7 = v13;
        }
        float v14 = v7;
        b1[v0] = v14;  // bounds witness 1, ownership witness 0
    }
}
