// Generated by tiler-metal from verified structured kernel IR.
// Deterministic output: do not edit.
//
// Metal Shading Language: metal3.1
// Artifact family: macos (deployment minimum 14.0)
// Launch index: [[thread_position_in_grid]] declared as uint
// Launch precondition: no invocation index may exceed 4294967295.
// Arithmetic subnormals, per floating-point type:
//   f32: flushes-to-zero-preserving-sign
//   f16: preserves-subnormals
//   bf16: flushes-to-zero-preserving-sign
//
// Carried by these operations under every math mode: every f32 immediate
// is its exact bit pattern, every arithmetic operation is one statement,
// and every NaN test is an integer test over reinterpreted bits.
//
// Declared numerical obligations this profile cannot realize:
//   subnormal-flush-in-arithmetic
// Arithmetic types used with no stated subnormal fact: none.

#include <metal_stdlib>
using namespace metal;

// Replaces an arithmetic NaN with the canonical pattern 0x7fc00000.
//
// The predicate is an integer test over the reinterpreted bit pattern rather
// than a floating-point one, so no math-mode relaxation licence reaches it.
static inline float tiler_canonicalize_nan_f32_7fc00000(float value) {
    uint pattern = as_type<uint>(value);
    bool nan = (pattern & 0x7f800000u) == 0x7f800000u
        && (pattern & 0x007fffffu) != 0x00000000u;
    return nan ? as_type<float>(0x7fc00000u) : value;
}

// Entry point tiler_kernel_8903b26b68f4162e
//   kernel identity digest: 8903b26b68f4162e
//   scheduled region identity digest: f852e4b8990a7ab6
//   numerical profile: tiler.test.strict-f32
//   buffer(0): Intermediate tensor, F32, Device space, Read access, 24 element(s)
//   buffer(1): Output tensor, F32, Device space, Write access, 2 element(s)
kernel void tiler_kernel_8903b26b68f4162e(
        device const float *b0 [[buffer(0)]],
        device float *b1 [[buffer(1)]],
        uint tiler_global_invocation_index [[thread_position_in_grid]]) {
    ulong v0 = ulong(tiler_global_invocation_index);  // widened from uint
    ulong v1 = 2ul;
    bool v2 = v0 < v1;
    if (v2) {
        ulong v3 = 12ul;
        ulong v4 = v0 * v3;
        float v5 = b0[v4];  // bounds witness 0
        // serial loop over [1, 12)
        ulong v6 = 1ul;
        float v7 = v5;
        for (; v6 < 12ul; v6 = v6 + 1ul) {
            ulong v8 = 12ul;
            ulong v9 = v0 * v8;
            ulong v10 = 4ul;
            ulong v11 = v6 / v10;
            ulong v12 = 4ul;
            ulong v13 = v11 * v12;
            ulong v14 = v9 + v13;
            ulong v15 = 4ul;
            ulong v16 = v6 % v15;
            ulong v17 = v14 + v16;
            float v18 = b0[v17];  // bounds witness 0
            float v19 = v7 + v18;
            float v20 = tiler_canonicalize_nan_f32_7fc00000(v19);
            v7 = v20;
        }
        float v21 = v7;
        b1[v0] = v21;  // bounds witness 1, ownership witness 0
    }
}
