// Generated by tiler-metal from verified structured kernel IR.
// Deterministic output: do not edit.
//
// Metal Shading Language: metal3.1
// Artifact family: macos (deployment minimum 13.0)
// Launch index: [[thread_position_in_grid]] declared as uint
// Launch precondition: no invocation index may exceed 4294967295.
//
// Every f32 immediate is emitted as its exact bit pattern, and every
// arithmetic operation is emitted as one statement, so neither literal
// parsing nor contraction across operations can change a result.

#include <metal_stdlib>
using namespace metal;

// Replaces an arithmetic NaN with the canonical pattern 0x7fc00000.
static inline float tiler_canonicalize_nan_f32_7fc00000(float value) {
    return isnan(value) ? as_type<float>(0x7fc00000u) : value;
}

// Entry point tiler_kernel_375c766b3db5a012
//   kernel identity digest: 375c766b3db5a012
//   scheduled region identity digest: f41ee169d570d82d
//   numerical profile: tiler.test.strict-f32
//   buffer(0): Intermediate tensor, F32, Device space, Read access, 24 element(s)
//   buffer(1): Output tensor, F32, Device space, Write access, 2 element(s)
kernel void tiler_kernel_375c766b3db5a012(
        device const float *b0 [[buffer(0)]],
        device float *b1 [[buffer(1)]],
        uint tiler_global_invocation_index [[thread_position_in_grid]]) {
    ulong v0 = ulong(tiler_global_invocation_index);  // widened from uint
    ulong v1 = 2ul;
    bool v2 = v0 < v1;
    if (v2) {
        ulong v3 = 12ul;
        ulong v4 = v0 * v3;
        float v5 = b0[v4];  // bounds witness 0
        // serial loop over [1, 12)
        ulong v6 = 1ul;
        float v7 = v5;
        for (; v6 < 12ul; v6 = v6 + 1ul) {
            ulong v8 = 12ul;
            ulong v9 = v0 * v8;
            ulong v10 = 4ul;
            ulong v11 = v6 / v10;
            ulong v12 = 4ul;
            ulong v13 = v11 * v12;
            ulong v14 = v9 + v13;
            ulong v15 = 4ul;
            ulong v16 = v6 % v15;
            ulong v17 = v14 + v16;
            float v18 = b0[v17];  // bounds witness 0
            float v19 = v7 + v18;
            float v20 = tiler_canonicalize_nan_f32_7fc00000(v19);
            v7 = v20;
        }
        float v21 = v7;
        b1[v0] = v21;  // bounds witness 1, ownership witness 0
    }
}
