// Generated by tiler-metal from verified structured kernel IR.
// Deterministic output: do not edit.
//
// Metal Shading Language: metal3.1
// Artifact family: macos (deployment minimum 14.0)
// Launch delivery realization: [[thread_position_in_grid]] declared as uint
// Structured index arithmetic: uint64_t, widened explicitly from uint delivery.
// Arithmetic subnormals, per floating-point type:
//   f32: flushes-to-zero-preserving-sign
//   f16: preserves-subnormals
//   bf16: flushes-to-zero-preserving-sign
//
// Carried by these operations under every math mode: every floating-point
// immediate is its exact bit pattern, every arithmetic operation is one
// statement, and every NaN test is an integer test over reinterpreted bits.
//
// Declared numerical obligations this profile cannot realize: none.
// Arithmetic types used with no stated subnormal fact: none.

#include <metal_stdlib>
using namespace metal;

// Entry point tiler_kernel_9489de3747a0a613
//   kernel identity digest: 9489de3747a0a613
//   scheduled region identity digest: 086f2f498331be7d
//   numerical profile: tiler.test.strict-f32
//   buffer(0): Input tensor, F32, Device space, Read access, 4 element(s)
//   buffer(1): Output tensor, F32, Device space, Write access, 4 element(s)
kernel void tiler_kernel_9489de3747a0a613(
        device const float *b0 [[buffer(0)]],
        device float *b1 [[buffer(1)]],
        uint tiler_global_invocation_index [[thread_position_in_grid]]) {
    uint64_t v0 = uint64_t(tiler_global_invocation_index);  // widened from uint
    uint64_t v1 = 4ul;
    bool v2 = v0 < v1;
    if (v2) {
        uint64_t v3 = 2ul;
        uint64_t v4 = v0 / v3;
        uint64_t v5 = 2ul;
        uint64_t v6 = v4 * v5;
        uint64_t v7 = 2ul;
        uint64_t v8 = v0 % v7;
        uint64_t v9 = 1ul;
        uint64_t v10 = v9 - v8;  // unsigned; v8 <= v9 by the IR's proof, not by a test
        uint64_t v11 = v6 + v10;
        float v12 = b0[v11];  // bounds witness 0
        b1[v0] = v12;  // bounds witness 1, ownership witness 0
    }
}
