// Generated by tiler-metal from verified structured kernel IR.
// Deterministic output: do not edit.
//
// Metal Shading Language: metal3.1
// Artifact family: macos (deployment minimum 14.0)
// Launch delivery realization: [[thread_position_in_grid]] declared as uint
// Structured index arithmetic: uint64_t, widened explicitly from uint delivery.
// Arithmetic subnormals, per floating-point type:
//   f32: flushes-to-zero-preserving-sign
//   f16: preserves-subnormals
//   bf16: flushes-to-zero-preserving-sign
//
// Carried by these operations under every math mode: every floating-point
// immediate is its exact bit pattern, every arithmetic operation is one
// statement, and every NaN test is an integer test over reinterpreted bits.
//
// Declared numerical obligations this profile cannot realize: none.
// Arithmetic types used with no stated subnormal fact: none.

#include <metal_stdlib>
using namespace metal;

// Entry point tiler_kernel_780ee8b88fd4f388
//   kernel identity digest: 780ee8b88fd4f388
//   scheduled region identity digest: 8d9fe9420b51cf4f
//   numerical profile: tiler.test.strict-f32
//   buffer(0): Input tensor, F32, Device space, Read access, 2 element(s)
//   buffer(1): Output tensor, F32, Device space, Write access, 4 element(s)
kernel void tiler_kernel_780ee8b88fd4f388(
        device const float *b0 [[buffer(0)]],
        device float *b1 [[buffer(1)]],
        uint tiler_global_invocation_index [[thread_position_in_grid]]) {
    uint64_t v0 = uint64_t(tiler_global_invocation_index);  // widened from uint
    uint64_t v1 = 4ul;
    bool v2 = v0 < v1;
    if (v2) {
        uint64_t v3 = 2ul;
        uint64_t v4 = v0 % v3;
        float v5 = b0[v4];  // bounds witness 0
        b1[v0] = v5;  // bounds witness 1, ownership witness 0
    }
}
