//! An out-of-tree consumer writes the approved region and gets its own tensor
//! back.
//!
//! This is the end-to-end case: a crate that depends on `tiler` alone declares
//! its own adapter over its own value type, writes
//!
//! ```text
//! sym n;
//! in a: f32[n], b: f32[n], c: f32[n];
//! out (a * b) + c
//! ```
//!
//! and evaluates it. Nothing here is generated by hand — the region's facts, the
//! binding call, and the result construction are all what `tiler::tensor!`
//! expanded to — and nothing in `tiler` had to change to accept this adapter.
//!
//! Three regions are exercised because they reach different halves of the
//! expansion: the symbolic one is the approved example and defers its public
//! logical program, the literal one is representable in the fixed-extent
//! semantic layer and is therefore constructed and verified at expansion time,
//! and the scalar one exercises the registry's broadcast rule.

use tiler::value::{
    AdapterCapability, BindError, OperandAxis, ResultRequest, StorageScalar, Tensor, TensorAdapter,
    ValueMetadata,
};

/// This consumer's own tensor. `tiler` never learns what is in it.
#[derive(Clone, Debug, PartialEq)]
struct Buffer {
    scalar: StorageScalar,
    extents: Vec<u64>,
}

/// This consumer's own error. `tiler` carries it and never replaces it.
#[derive(Clone, Debug, PartialEq)]
struct Refused(&'static str);

impl core::fmt::Display for Refused {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter.write_str(self.0)
    }
}

impl std::error::Error for Refused {}

/// The adapter. A type, not a registration: nothing global learns it exists.
struct Toy;

impl TensorAdapter for Toy {
    type Value = Buffer;
    type Context = ();
    type Error = Refused;

    fn supports(capability: AdapterCapability) -> bool {
        match capability {
            AdapterCapability::DenseRowMajorStorage | AdapterCapability::ResultConstruction => true,
        }
    }

    fn metadata(value: &Buffer) -> Result<ValueMetadata, Refused> {
        Ok(ValueMetadata::new(
            value.scalar,
            value.extents.iter().copied(),
        ))
    }

    fn build(_: &(), request: &ResultRequest<'_>) -> Result<Buffer, Refused> {
        Ok(Buffer {
            scalar: request.storage_scalar(),
            extents: request.extents().to_vec(),
        })
    }
}

fn f32_tensor(extents: &[u64]) -> Tensor<Toy> {
    Tensor::new(
        Buffer {
            scalar: StorageScalar::F32,
            extents: extents.to_vec(),
        },
        (),
    )
}

fn u8_tensor(extents: &[u64]) -> Tensor<Toy> {
    Tensor::new(
        Buffer {
            scalar: StorageScalar::U8,
            extents: extents.to_vec(),
        },
        (),
    )
}

fn main() {
    // The approved example, with a symbolic extent bound from operand metadata.
    let (a, b, c) = (f32_tensor(&[5]), f32_tensor(&[5]), f32_tensor(&[5]));
    let d = tiler::tensor! {
        sym n;
        in a: f32[n], b: f32[n], c: f32[n];
        contract flush_subnormals_to_zero_f32;
        out (a * b) + c
    };
    assert_eq!(
        d.expect("every operand reports extent 5"),
        Buffer {
            scalar: StorageScalar::F32,
            extents: vec![5],
        },
        "the region's result is `f32[n]` with `n` bound from `a` axis 0",
    );

    // The same region refuses when two axes naming one symbol disagree, and the
    // refusal names both operands a consumer wrote rather than their positions.
    let refused = {
        let b = f32_tensor(&[6]);
        tiler::tensor! {
            sym n;
            in a: f32[n], b: f32[n], c: f32[n];
            contract flush_subnormals_to_zero_f32;
            out (a * b) + c
        }
    };
    assert_eq!(
        refused.expect_err("`b` axis 0 owes `a` axis 0 an equality"),
        BindError::InconsistentExtent {
            symbol: "n",
            source: OperandAxis {
                input: "a",
                axis: 0,
            },
            source_extent: 5,
            conflicting: OperandAxis {
                input: "b",
                axis: 0,
            },
            conflicting_extent: 6,
        },
    );

    // A stored scalar the region did not declare is refused, naming the operand.
    let mismatched = {
        let b = u8_tensor(&[5]);
        tiler::tensor! {
            sym n;
            in a: f32[n], b: f32[n], c: f32[n];
            contract flush_subnormals_to_zero_f32;
            out (a * b) + c
        }
    };
    assert_eq!(
        mismatched.expect_err("`b` is declared `f32`"),
        BindError::StorageScalarMismatch {
            input: "b",
            declared: StorageScalar::F32,
            actual: StorageScalar::U8,
        },
    );

    // A region whose every extent is a literal is representable in the
    // fixed-extent semantic layer, so its public logical program was
    // constructed and verified while this file was being compiled.
    let fixed = {
        let (a, b, c) = (f32_tensor(&[4]), f32_tensor(&[4]), f32_tensor(&[4]));
        tiler::tensor! {
            in a: f32[4], b: f32[4], c: f32[4];
            contract flush_subnormals_to_zero_f32;
            out (a * b) + c
        }
    };
    assert_eq!(
        fixed.expect("every operand reports extent 4").extents,
        vec![4],
    );

    // A literal extent the supplied value does not report is refused at run
    // time, naming the axis. The region's shape claim is checked rather than
    // assumed: without this the result would be constructed at the *declared*
    // `[4]` from a value holding seven elements.
    let wrong_extent = {
        let (a, b, c) = (f32_tensor(&[7]), f32_tensor(&[4]), f32_tensor(&[4]));
        tiler::tensor! {
            in a: f32[4], b: f32[4], c: f32[4];
            contract flush_subnormals_to_zero_f32;
            out (a * b) + c
        }
    };
    assert_eq!(
        wrong_extent.expect_err("`a` is declared `f32[4]`"),
        BindError::LiteralExtentMismatch {
            axis: OperandAxis {
                input: "a",
                axis: 0,
            },
            declared: 4,
            actual: 7,
        },
    );

    // Its neighbour perturbs the rank instead, which is a different check and a
    // different refusal.
    let wrong_rank = {
        let (a, b, c) = (f32_tensor(&[4, 1]), f32_tensor(&[4]), f32_tensor(&[4]));
        tiler::tensor! {
            in a: f32[4], b: f32[4], c: f32[4];
            contract flush_subnormals_to_zero_f32;
            out (a * b) + c
        }
    };
    assert_eq!(
        wrong_rank.expect_err("`a` is declared rank 1"),
        BindError::RankMismatch {
            input: "a",
            declared: 1,
            actual: 2,
        },
    );

    // A region that reduces: the result's *rank* is what the region denotes, so
    // the value this consumer gets back is rank 1 from a rank-2 operand. The
    // axis is named in the shape that declares it, and the constant beside it is
    // an ordinary real number.
    let reduced = {
        let x = f32_tensor(&[2, 3]);
        tiler::tensor! {
            in x: f32[rows: 2, cols: 3];
            contract flush_subnormals_to_zero_f32;
            out strict_serial_sum(x * 2.0 + 1.0, [cols])
        }
    };
    assert_eq!(
        reduced.expect("`x` reports `[2, 3]`").extents,
        vec![2],
        "summing `cols` leaves `f32[rows]`",
    );

    // Reducing every axis leaves a rank-0 result.
    let scalar_result = {
        let x = f32_tensor(&[2, 3]);
        tiler::tensor! {
            in x: f32[rows: 2, cols: 3];
            contract flush_subnormals_to_zero_f32;
            out strict_serial_sum(x * 2.0 + -1.5, [rows, cols])
        }
    };
    assert_eq!(
        scalar_result.expect("`x` reports `[2, 3]`").extents,
        Vec::<u64>::new(),
    );

    // A symbolic extent survives the reduction of the axis beside it, and is
    // still bound from operand metadata at run time.
    let symbolic_reduction = {
        let x = f32_tensor(&[5, 3]);
        tiler::tensor! {
            sym n;
            in x: f32[n, cols: 3];
            contract flush_subnormals_to_zero_f32;
            out strict_serial_sum(x * 2.0 + 1.0, [cols])
        }
    };
    assert_eq!(
        symbolic_reduction
            .expect("`n` binds to 5 from `x` axis 0")
            .extents,
        vec![5],
    );

    // An axis is named rather than counted: a symbolic extent is already a name,
    // so `n` reduces without a second spelling for it.
    let named_by_symbol = {
        let x = f32_tensor(&[3, 5]);
        tiler::tensor! {
            sym n;
            in x: f32[cols: 3, n];
            contract flush_subnormals_to_zero_f32;
            out strict_serial_sum(x * 2.0 + 1.0, [n])
        }
    };
    assert_eq!(
        named_by_symbol
            .expect("`n` binds to 5 from `x` axis 1")
            .extents,
        vec![3],
        "summing the symbolic axis leaves the literal one",
    );

    // A rank-0 operand broadcasts, and the result takes the shaped side.
    let scaled = {
        let (a, s) = (f32_tensor(&[3]), f32_tensor(&[]));
        tiler::tensor! {
            sym n;
            in a: f32[n], s: f32[];
            contract flush_subnormals_to_zero_f32;
            out a * s
        }
    };
    assert_eq!(
        scaled.expect("the scalar broadcasts").extents,
        vec![3],
        "`f32[n] * f32[]` is `f32[n]`",
    );

    let _ = (a, b, c);
}
