[package]
name = "tiler-macros"
description = "Procedural macro implementation for Tiler's inline tensor regions"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
proc-macro = true
test = true
doctest = true
doc = true

[lints]
workspace = true
