[package]
name = "tiler-compiler"
description = "Target-independent optimization and scheduling for Tiler"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
test = true
doctest = true
doc = true

[dependencies]
num-bigint.workspace = true
num-integer.workspace = true
num-traits.workspace = true
tiler-ir.workspace = true

[dev-dependencies]
tiler-reference.workspace = true

[lints]
workspace = true
